//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaLabv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public int UserEmployeeId { get; set; }
        public int UserTypeId { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public int GenderId { get; set; }
        public string Qualification { get; set; }
        public string AddressDetail { get; set; }
        public string CNIC { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual UserEmployee UserEmployee { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
