//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaLabv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.PatientRefers = new HashSet<PatientRefer>();
            this.PatientTests = new HashSet<PatientTest>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public string PatientName { get; set; }
        public string PatientNumber { get; set; }
        public System.DateTime DateTime { get; set; }
        public int GenderId { get; set; }
        public string Age { get; set; }
        public string Months { get; set; }
        public string Days { get; set; }
        public string Email { get; set; }
        public int BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<PatientRefer> PatientRefers { get; set; }
        public virtual ICollection<PatientTest> PatientTests { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
