//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaLabv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public string PatientName { get; set; }
        public double PaidAmount { get; set; }
        public double NetAmount { get; set; }
        public double Balance { get; set; }
        public int PayTypeId { get; set; }
        public double Discount { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual PayType PayType { get; set; }
    }
}
