//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaLabv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCategory
    {
        public TestCategory()
        {
            this.TestSubcategories = new HashSet<TestSubcategory>();
        }
    
        public int Id { get; set; }
        public string TestCategoryCode { get; set; }
        public string TestName { get; set; }
        public int TestDepartmentId { get; set; }
    
        public virtual TestDepartment TestDepartment { get; set; }
        public virtual ICollection<TestSubcategory> TestSubcategories { get; set; }
    }
}
